name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Validate JavaScript
      run: node -c yawc.js

    - name: Create Release Archive
      run: |
        mkdir -p yawc
        cp yawc.js yawc/
        cp README.md yawc/
        cp LICENSE yawc/
        cp hacs.json yawc/
        zip -r yawc-${{ github.ref_name }}.zip yawc/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          yawc-${{ github.ref_name }}.zip
          yawc.js
        generate_release_notes: true
        body: |
          ## YAWC ${{ github.ref_name }}
          
          Yet Another Weather Card - Advanced NWS weather integration for Home Assistant
          
          ### Installation via HACS
          1. Add this repository to HACS custom repositories
          2. Install "YAWC - Yet Another Weather Card"
          3. Add the card to your dashboard
          
          ### Manual Installation
          1. Download `yawc.js` from this release
          2. Copy to your `www` folder
          3. Add as a resource in your Lovelace configuration
          
          See the [README](https://github.com/${{ github.repository }}/blob/main/README.md) for full documentation.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate HACS
      run: |
        # Validate hacs.json structure
        cat hacs.json | jq empty
        
        # Check required files exist
        test -f yawc.js || exit 1
        test -f README.md || exit 1
        test -f LICENSE || exit 1
        
        # Validate JavaScript syntax
        node -c yawc.js

    - name: Check file sizes
      run: |
        # Ensure main file isn't too large
        size=$(stat -c%s "yawc.js")
        if [ $size -gt 200000 ]; then
          echo "Warning: yawc.js is larger than 200KB ($size bytes)"
        fi
        echo "File size: $size bytes"